### ISSUE TITLE
Property 'shape' does not exist on type 'ObjectType<{ ... }>'

### ISSUE THREAD

**Issue by kaedub** [davidmdm/myzod#12]
```
import myzod from "myzod";
const schema = myzod.object({name: myzod.string()});
const shape = schema.shape();
// Property 'shape' does not exist on type 'ObjectType<{ name: StringType; }>'
```

For now I am doing a workaround by accessing `objectShape` and just ignoring the private variable message in my editor.

**Comment by pierreis** [comment]
I cannot reproduce the error. With `1.0.0-alpha.8`:

```ts
import * as z from "myzod";
const o = z.object({ test: z.string() });
console.log(o.shape()); // => correctly returns the shape
```

Which version of the library are you using?

**Comment by kaedub** [comment]
I am using `1.0.0-alpha.2` I will try updating.

**Comment by pierreis** [comment]
That should fix the issue. `ObjectType.shape` was introduced in `v1.0.0-alpha.7`.

**Comment by davidmdm** [comment]
@kaedub, if updating has fixed the issue for you let me know! Otherwise I will close this issue.
Thanks for using myzod and please feel free to give any feedback you may have.

**Comment by kaedub** [comment]
I think it is okay you closed the issue as it seems like something done wrong on my end. I updated myzod to 1.0.0-alpha.8 but I am still getting the error. I have tried 1.0.0-alpha.9 as well to no avail.

**Comment by kaedub** [comment]
Updating to alpha.8 fixed this issue. Also had an error because I was trying to access shape() on a `Type` object instead of `ObjectType`. Thanks a lot!
